# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alexey/project/synfloodprotect

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alexey/project/synfloodprotect

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexey/project/synfloodprotect/CMakeFiles /home/alexey/project/synfloodprotect/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alexey/project/synfloodprotect/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bridge

# Build rule for target.
bridge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bridge
.PHONY : bridge

# fast build rule for target.
bridge/fast:
	$(MAKE) -f CMakeFiles/bridge.dir/build.make CMakeFiles/bridge.dir/build
.PHONY : bridge/fast

#=============================================================================
# Target rules for targets named logger

# Build rule for target.
logger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logger
.PHONY : logger

# fast build rule for target.
logger/fast:
	$(MAKE) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/build
.PHONY : logger/fast

#=============================================================================
# Target rules for targets named parcer

# Build rule for target.
parcer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parcer
.PHONY : parcer

# fast build rule for target.
parcer/fast:
	$(MAKE) -f CMakeFiles/parcer.dir/build.make CMakeFiles/parcer.dir/build
.PHONY : parcer/fast

#=============================================================================
# Target rules for targets named synfloodprotect

# Build rule for target.
synfloodprotect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synfloodprotect
.PHONY : synfloodprotect

# fast build rule for target.
synfloodprotect/fast:
	$(MAKE) -f CMakeFiles/synfloodprotect.dir/build.make CMakeFiles/synfloodprotect.dir/build
.PHONY : synfloodprotect/fast

bridge.o: bridge.cpp.o
.PHONY : bridge.o

# target to build an object file
bridge.cpp.o:
	$(MAKE) -f CMakeFiles/bridge.dir/build.make CMakeFiles/bridge.dir/bridge.cpp.o
.PHONY : bridge.cpp.o

bridge.i: bridge.cpp.i
.PHONY : bridge.i

# target to preprocess a source file
bridge.cpp.i:
	$(MAKE) -f CMakeFiles/bridge.dir/build.make CMakeFiles/bridge.dir/bridge.cpp.i
.PHONY : bridge.cpp.i

bridge.s: bridge.cpp.s
.PHONY : bridge.s

# target to generate assembly for a file
bridge.cpp.s:
	$(MAKE) -f CMakeFiles/bridge.dir/build.make CMakeFiles/bridge.dir/bridge.cpp.s
.PHONY : bridge.cpp.s

lib/logger/logger.o: lib/logger/logger.cpp.o
.PHONY : lib/logger/logger.o

# target to build an object file
lib/logger/logger.cpp.o:
	$(MAKE) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/lib/logger/logger.cpp.o
.PHONY : lib/logger/logger.cpp.o

lib/logger/logger.i: lib/logger/logger.cpp.i
.PHONY : lib/logger/logger.i

# target to preprocess a source file
lib/logger/logger.cpp.i:
	$(MAKE) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/lib/logger/logger.cpp.i
.PHONY : lib/logger/logger.cpp.i

lib/logger/logger.s: lib/logger/logger.cpp.s
.PHONY : lib/logger/logger.s

# target to generate assembly for a file
lib/logger/logger.cpp.s:
	$(MAKE) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/lib/logger/logger.cpp.s
.PHONY : lib/logger/logger.cpp.s

lib/parser/fastnetmon_packet_parser.o: lib/parser/fastnetmon_packet_parser.c.o
.PHONY : lib/parser/fastnetmon_packet_parser.o

# target to build an object file
lib/parser/fastnetmon_packet_parser.c.o:
	$(MAKE) -f CMakeFiles/parcer.dir/build.make CMakeFiles/parcer.dir/lib/parser/fastnetmon_packet_parser.c.o
.PHONY : lib/parser/fastnetmon_packet_parser.c.o

lib/parser/fastnetmon_packet_parser.i: lib/parser/fastnetmon_packet_parser.c.i
.PHONY : lib/parser/fastnetmon_packet_parser.i

# target to preprocess a source file
lib/parser/fastnetmon_packet_parser.c.i:
	$(MAKE) -f CMakeFiles/parcer.dir/build.make CMakeFiles/parcer.dir/lib/parser/fastnetmon_packet_parser.c.i
.PHONY : lib/parser/fastnetmon_packet_parser.c.i

lib/parser/fastnetmon_packet_parser.s: lib/parser/fastnetmon_packet_parser.c.s
.PHONY : lib/parser/fastnetmon_packet_parser.s

# target to generate assembly for a file
lib/parser/fastnetmon_packet_parser.c.s:
	$(MAKE) -f CMakeFiles/parcer.dir/build.make CMakeFiles/parcer.dir/lib/parser/fastnetmon_packet_parser.c.s
.PHONY : lib/parser/fastnetmon_packet_parser.c.s

lib/parser/parcer.o: lib/parser/parcer.cpp.o
.PHONY : lib/parser/parcer.o

# target to build an object file
lib/parser/parcer.cpp.o:
	$(MAKE) -f CMakeFiles/parcer.dir/build.make CMakeFiles/parcer.dir/lib/parser/parcer.cpp.o
.PHONY : lib/parser/parcer.cpp.o

lib/parser/parcer.i: lib/parser/parcer.cpp.i
.PHONY : lib/parser/parcer.i

# target to preprocess a source file
lib/parser/parcer.cpp.i:
	$(MAKE) -f CMakeFiles/parcer.dir/build.make CMakeFiles/parcer.dir/lib/parser/parcer.cpp.i
.PHONY : lib/parser/parcer.cpp.i

lib/parser/parcer.s: lib/parser/parcer.cpp.s
.PHONY : lib/parser/parcer.s

# target to generate assembly for a file
lib/parser/parcer.cpp.s:
	$(MAKE) -f CMakeFiles/parcer.dir/build.make CMakeFiles/parcer.dir/lib/parser/parcer.cpp.s
.PHONY : lib/parser/parcer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/synfloodprotect.dir/build.make CMakeFiles/synfloodprotect.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/synfloodprotect.dir/build.make CMakeFiles/synfloodprotect.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/synfloodprotect.dir/build.make CMakeFiles/synfloodprotect.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bridge"
	@echo "... edit_cache"
	@echo "... logger"
	@echo "... parcer"
	@echo "... rebuild_cache"
	@echo "... synfloodprotect"
	@echo "... bridge.o"
	@echo "... bridge.i"
	@echo "... bridge.s"
	@echo "... lib/logger/logger.o"
	@echo "... lib/logger/logger.i"
	@echo "... lib/logger/logger.s"
	@echo "... lib/parser/fastnetmon_packet_parser.o"
	@echo "... lib/parser/fastnetmon_packet_parser.i"
	@echo "... lib/parser/fastnetmon_packet_parser.s"
	@echo "... lib/parser/parcer.o"
	@echo "... lib/parser/parcer.i"
	@echo "... lib/parser/parcer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

